// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwcBGDIXqolgOFMs2YZLRTwWUzdharkZk',
    appId: '1:327791600118:web:fcc1665cd8002e574ca7d7',
    messagingSenderId: '327791600118',
    projectId: 'aklo-cafe',
    authDomain: 'aklo-cafe.firebaseapp.com',
    storageBucket: 'aklo-cafe.appspot.com',
    measurementId: 'G-KGW1W72FSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPoK6e3Tqytn94OACk6ZzgEaLAw0sKm04',
    appId: '1:327791600118:android:c91a2940ac70c4764ca7d7',
    messagingSenderId: '327791600118',
    projectId: 'aklo-cafe',
    storageBucket: 'aklo-cafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuEdkznRhPoD6l45oypwMhRU8qZ57iYvs',
    appId: '1:327791600118:ios:03f4bcbedcc278774ca7d7',
    messagingSenderId: '327791600118',
    projectId: 'aklo-cafe',
    storageBucket: 'aklo-cafe.appspot.com',
    iosClientId: '327791600118-kk2k4ffvpnq4iqh90h7sm39rvmgf8mjr.apps.googleusercontent.com',
    iosBundleId: 'com.aklocafe.app',
  );
}
